name: multistage pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'building'
  test:
    runs-on: ubunut-latest
    steps:
       - run: echo 'testing'
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo 'deployment'


    
